webtalk_init -webtalk_dir C:/Users/jc170/Documents/Vivado Projects/Homebew_Console/VGA_Controller.sim/sim_1/behav/xsim/xsim.dir/vga_controller_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 27 21:42:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5f16e1a0-ecf7-4b84-ae26-86b66029144a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3582165413f04b888d97708ff46a105a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "117" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "16.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14724_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3684835959 -regid "" -xml C:/Users/jc170/Documents/Vivado Projects/Homebew_Console/VGA_Controller.sim/sim_1/behav/xsim/xsim.dir/vga_controller_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jc170/Documents/Vivado Projects/Homebew_Console/VGA_Controller.sim/sim_1/behav/xsim/xsim.dir/vga_controller_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jc170/Documents/Vivado Projects/Homebew_Console/VGA_Controller.sim/sim_1/behav/xsim/xsim.dir/vga_controller_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
